### ISSUE TITLE
Not working for vite 5

### ISSUE THREAD

**Issue by aldiand** [jozefizso/vite-plugin-office-addin#5]
$ tsc && vite build
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
failed to load config from /Users/andre/Documents/GitHub/OfficeSmartAssist/vite.config.ts
error during build:
TypeError: officeAddin is not a function
    at file:///Users/andre/Documents/GitHub/OfficeSmartAssist/vite.config.ts.timestamp-1702663364583-8bb8b70a973c4.mjs:12:32
    at loadConfigFromFile (file:///Users/andre/Documents/GitHub/OfficeSmartAssist/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:67875:15)
    at async resolveConfig (file:///Users/andre/Documents/GitHub/OfficeSmartAssist/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:67473:28)
    at async build (file:///Users/andre/Documents/GitHub/OfficeSmartAssist/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:66645:20)
    at async CAC.<anonymous> (file:///Users/andre/Documents/GitHub/OfficeSmartAssist/node_modules/vite/dist/node/cli.js:845:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jozefizso** [comment]
Contributions to fix the bug are welcome.

**Comment by jozefizso** [comment]
Published in [v2.0.0](https://github.com/jozefizso/vite-plugin-office-addin/releases/tag/v2.0.0)
